Repository Gamify-IT/docs, pull requests merged in 2022-06, with the labels that each got.

#18 add SonarQube-access meeting protocol
  protocols/devops/2022-06-01-protocol.md
Labels: documentation

#30 add meeting transcript 03.06.2022
  protocols/devops/2022-06-03-protocol.md
Labels: documentation

#33 Add three additional ADRs and an ADR template
  adr/adr-template.md
  adr/inter-team-communication.md
  adr/minigame-guide.md
  adr/organizational-structure.md
Labels: documentation

#35 added protocol for prof-interface meeting
  protocols/prof-interface/2022-06-14-prof-interface-sketch-popup.png
  protocols/prof-interface/2022-06-14-prof-interface-sketch.png
  protocols/prof-interface/2022-06-14-protocol.md
Labels: documentation

#39 Fix all Sphinx warnings
  protocols/global/2022-06-03-protocol-2-planning.md
  protocols/index.rst
  protocols/lecturer-interface/2022-06-14-prof-interface-sketch-popup.png
  protocols/lecturer-interface/2022-06-14-prof-interface-sketch.png
  protocols/lecturer-interface/2022-06-14-protocol.md
Labels: bug, documentation

#44 Define when to use each column in our sprint board
  adr/sprint-board-workflow.md
Labels: documentation

#46 Define database type and data model for overworld
  dev-manuals/services/overworld/database-model-and-type.md
Labels: documentation

#43 created UML class diagram for the overworld
  dev-manuals/services/overworld/class-diagram/overworld-class-diagram.drawio
  dev-manuals/services/overworld/class-diagram/overworld-class-diagram.png
Labels: documentation, feature

#55 Update glossary
  internal/glossary.md
Labels: documentation

#52 document role change between @madebyTimo and @IlijazM
  internal/agile-charter.md
  internal/responsibilities.md
Labels: documentation

#57 Create 2022-06-27-protocol.md
  protocols/global/2022-06-27-protocol.md
Labels: documentation
