Repository Gamify-IT/docs, pull requests merged in 2022-09, with the labels that each got.

#148 Add import and export testplan for minigame configurations in lecturer interface
  dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-28-import-export-minigame-configuration.md
Labels: documentation

#151 Add code review protocol (16.09.2022)
  protocols/global/2022-09-16-code-review-protocol.md
Labels: documentation

#158 How to integrate a new minigame
  dev-manuals/services/integrate-new-minigame.md
Labels: documentation

#162 add overworld user and developer readme
  dev-manuals/services/overworld/README.md
  images/keybindings.webp
  images/minigame-spot.webp
  images/npc-dialogue.webp
  user-manuals/overworld/README.md
Labels: documentation

#168 Add configurable books to the overworld database model
  dev-manuals/services/overworld/database-model-and-type.md
  dev-manuals/services/overworld/database-model/database-model.drawio
  dev-manuals/services/overworld/database-model/database-model.png
  dev-manuals/services/overworld/database-model/database-model.svg
Labels: documentation

#165 Document the general Gamify-IT architecture and fix two ReadTheDocs warnings
  dev-manuals/architecture/diagrams/component-diagram.svg
  dev-manuals/architecture/diagrams/gamify-it-architecture.svg
  dev-manuals/architecture/diagrams/sequence-diagram.svg
  dev-manuals/architecture/general-architecture.md
  dev-manuals/services/component-diagram_(editable-with-drawio).png
  dev-manuals/services/integrate-new-minigame.md
  dev-manuals/services/sequence-diagram_(editable-with-drawio).png
Labels: documentation

#169 Add test plans for book configuration view
  dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-29-show-books-of-area.md
  dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-30-edit-book-configuration.md
Labels: documentation

#171 Create user manual for the lecturer interface
  user-manuals/lecturer-interface/README.md
  user-manuals/lecturer-interface/assets/book-view.webp
  user-manuals/lecturer-interface/assets/course-overview.webp
  user-manuals/lecturer-interface/assets/courses-list.webp
  user-manuals/lecturer-interface/assets/create-course-modal.webp
  user-manuals/lecturer-interface/assets/created-course.webp
  user-manuals/lecturer-interface/assets/minigame-view.webp
  user-manuals/lecturer-interface/assets/npc-view.webp
  user-manuals/lecturer-interface/assets/world-map.webp
  user-manuals/lecturer-interface/assets/world-overview.webp
Labels: documentation

#176 Add bugfinder user manual
  user-manuals/minigames/assets/bugfinder-end-screen.webp
  user-manuals/minigames/assets/bugfinder-feedback.webp
  user-manuals/minigames/assets/bugfinder-fix-bug.webp
  user-manuals/minigames/assets/bugfinder-game-screen.webp
  user-manuals/minigames/assets/bugfinder-start-screen.webp
  user-manuals/minigames/bugfinder.md
Labels: documentation

#177 Add bugfinder install manual
  install-manuals/minigames/bugfinder.md
Labels: documentation

#174 Add various ReadTheDocs improvements
  conf.py
  dev-manuals/etc/glossary.md
  dev-manuals/index.rst
  dev-manuals/services/overworld/world-loaders.md
  requirements.txt
Labels: feature

#161 Add world 2, 3, and 4 maps
  user-manuals/index.rst
  user-manuals/maps/maps.md
  user-manuals/maps/world2/books.webp
  user-manuals/maps/world2/dungeons.webp
  user-manuals/maps/world2/minigames.webp
  user-manuals/maps/world2/npc.webp
  user-manuals/maps/world2/raw.webp
  user-manuals/maps/world3/books.webp
  user-manuals/maps/world3/dungeons.webp
  user-manuals/maps/world3/minigames.webp
  user-manuals/maps/world3/npc.webp
  user-manuals/maps/world3/raw.webp
  user-manuals/maps/world4/books.webp
  user-manuals/maps/world4/dungeons.webp
  user-manuals/maps/world4/minigames.webp
  user-manuals/maps/world4/npc.webp
  user-manuals/maps/world4/raw.webp
Labels: documentation

#182 Remove @delvh from codeowners
  CODEOWNERS
Labels: bug

#178 Add overworld install manual
  install-manuals/overworld/overworld.md
Labels: documentation
