Repository Gamify-IT/docs, pull requests merged in 2022-07, with the labels that each got.

#65 Document pending unity license change
  dev-manuals/languages/unity/license-change-information.md
Labels: documentation

#63 Add Component diagram
  dev-manuals/services/component-diagram_(editable-with-drawio).png
Labels: documentation, feature

#67 Add project manager duty checklist
  dev-manuals/project-management/project-manager-duty-checklist.md
Labels: documentation

#69 Draw sequence diagram
  dev-manuals/services/sequence-diagram_(editable-with-drawio).png
Labels: feature

#80 Add tools for java
  dev-manuals/languages/java/README.md
  dev-manuals/languages/java/code-format.md
  dev-manuals/languages/java/lombok.md
  dev-manuals/languages/java/mapping-objects.md
Labels: documentation

#84 Update project manager checklist and fix ReadTheDocs warnings
  dev-manuals/languages/unity/setup-tilemap-in-unity.md
  dev-manuals/project-management/project-manager-duty-checklist.md
  dev-manuals/services/login-backend/README.md
  dev-manuals/sonarqube/5_how-to-sonar-testcoverage.md
  protocols/global/2022-06-03-protocol-2-planning.md
  user-manuals/index.rst
Labels: documentation

#85 Enhance data model for overworld backend
  dev-manuals/services/overworld/class-diagram/overworld-class-diagram.drawio
  dev-manuals/services/overworld/class-diagram/overworld-class-diagram.png
  dev-manuals/services/overworld/database-model-and-type.md
  dev-manuals/services/overworld/database-model/database-model.drawio
  dev-manuals/services/overworld/database-model/database-model.png
Labels: documentation

#83 ADR: How to handle minigame configuration ID as URL route
  adr/2022-07-17-minigame-configuration-id-in-url.md
Labels: ADR

#82 ADR: Format of minigame configuration IDs
  adr/2022-07-17-minigame-configuration-id-format.md
Labels: ADR

#89 ADR: API paths on run-config
  adr/2022-07-21-api-paths.md
Labels: ADR

#86 Add yet another project manager task
  dev-manuals/project-management/project-manager-duty-checklist.md
Labels: documentation

#93 Add chosen solution to "run-config API Paths" ADR
  adr/2022-07-21-api-paths.md
Labels: bug

#88 Document how to use springdoc-openapi
  dev-manuals/languages/java/README.md
  dev-manuals/languages/java/code-format.md
  dev-manuals/languages/java/lombok.md
  dev-manuals/languages/java/mapping-objects.md
  dev-manuals/languages/java/springdoc.md
Labels: documentation

#94 Adapt project manager tasks (once again)
  dev-manuals/project-management/project-manager-duty-checklist.md
Labels: documentation

#91 ADR: Which Java version do we use?
  adr/2022-07-22-java-version.md
Labels: ADR

#92 ADR: How to spell acronyms in code
  adr/2022-06-03-issues-repository.md
  adr/2022-07-26-spelling-of-id.md
Labels: ADR

#87 improve database model
  dev-manuals/services/overworld/database-model-and-type.md
  dev-manuals/services/overworld/database-model/database-model.drawio
  dev-manuals/services/overworld/database-model/database-model.png
Labels: documentation
